language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 002c9d6c8d2575f00ea1e5eefabe21e45441c22357bfb5ad2c93887339cec084
